export const STATUS = {
  PROCESS: "PROCESS",
  PICKING: "PICKING",
  DONE: "DONE",
  CREATED: "CREATED",
};

export const HTTP_STATUS = {
  NOT_FOUND: 404,
  SUCCESS: 200,
  SYSTEM_ERROR: 500,
  UNAUTHORIZED: 401,
  BAD_REQUEST: 400,
  SUCESS_NO_DATA: 201,
  SUCCESS_COMPLETED: 202,
};
